site_name: MIKUMARI User Guide
site_description: MIKUMARI User Guide
site_author: "R.Honda"
repo_url: https://github.com/RyotaroHonda/ug-mikumari
repo_name: ug-mikumari

theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
  palette:
    #    scheme: slate
    scheme: default
    primary: cyan

markdown_extensions:
  - attr_list
  - def_list
  - markdown_katex:
      no_inline_svg: true
      insert_fonts_css: true
  #  - hbfm.inline_coloring
  #  - hbfm.inline_list
  #  - toc:
  #      slugify: !!python/name:hbfm.toc.slugify
  #- hbfm.number_headers
  #- hbfm.quote_uri_hash
  - image_captions:
      numbering: true
  - caption:
      numbering: true

extra_css:
  - css/custom.css

nav:
  - Top: index.md
  - Release: release/release.md
  - Get-Started: get-started/main.md
  - CBT: cbt/cbt.md
  - Mikumari-Link: mikumari-link/link.md
#  - Software: software/main.md
#  - Practical Usage: practical/main.md
